AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for AWS Managed Grafana

Resources:

  GrafanaWorkspaceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: managed-grafana-workspace-role

      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - grafana.amazonaws.com
            Action:
              - sts:AssumeRole

      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess

Outputs:

  GrafanaWorkspaceRoleArn:
    Value: !GetAtt GrafanaWorkspaceRole.Arn
